import os
import sys
from pathlib import Path

_PROJECT_ROOT = str(Path(__file__).resolve().parent.parent)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from crewai import LLM, Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task

from config import ACTIVE_MODEL, CEREBRAS_API_KEY, OUTPUT_DIR, REPORT_FILENAME
from rag import embedder, retriever


def _make_llm() -> LLM:
    return LLM(
        model=ACTIVE_MODEL,
        api_key=CEREBRAS_API_KEY,
        temperature=0.3,
        max_tokens=2048,
    )


def _save_report(outputs: dict) -> str:

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    report_path = os.path.join(OUTPUT_DIR, REPORT_FILENAME)

    report = report = f"""# 🎯 Job Application Analysis Report

   ---

   ## 📄 1. Resume Analysis

   {outputs.get("resume_analysis", "Not available")}

   ---

   ## 📋 2. Job Description Analysis

   {outputs.get("jd_analysis", "Not available")}

   ---

   ## 🔍 3. Skills Gap Analysis

   {outputs.get("gap_analysis", "Not available")}

   ---

   ## 📚 4. Learning & Skills Upgrade Plan

   {outputs.get("skills_plan", "Not available")}

   ---

   ## ✍️ 5. Tailored Cover Letter

   {outputs.get("cover_letter", "Not available")}

   ---
   *Generated by Job Landing Assistant | Prototype 1*
   *Model: {ACTIVE_MODEL} | RAG: ChromaDB + all-MiniLM-L6-v2*
   """
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"   ✅ Report saved → {report_path}")
    return report_path


@CrewBase
class JobCrew:
    agents_config = "config/agents.yaml"
    tasks_config = "config/tasks.yaml"

    def __init__(self, llm: LLM):

        self.llm = llm

    @agent
    def resume_analyst(self) -> Agent:

        return Agent(
            config=self.agents_config["resume_analyst"],
            llm=self.llm,
            verbose=True,
            allow_delegation=False,
        )

    @agent
    def jd_analyzer(self) -> Agent:
        return Agent(
            config=self.agents_config["jd_analyzer"],
            llm=self.llm,
            verbose=True,
            allow_delegation=False,
        )

    @agent
    def gap_finder(self) -> Agent:
        return Agent(
            config=self.agents_config["gap_finder"],
            llm=self.llm,
            verbose=True,
            allow_delegation=False,
        )

    @agent
    def skills_advisor(self) -> Agent:
        return Agent(
            config=self.agents_config["skills_advisor"],
            llm=self.llm,
            verbose=True,
            allow_delegation=False,
        )

    @agent
    def cover_letter_writer(self) -> Agent:
        return Agent(
            config=self.agents_config["cover_letter_writer"],
            llm=self.llm,
            verbose=True,
            allow_delegation=False,
        )

    @task
    def resume_analysis_task(self) -> Task:

        return Task(
            config=self.tasks_config["resume_analysis_task"],
            agent=self.resume_analyst(),
        )

    @task
    def jd_analysis_task(self) -> Task:

        return Task(
            config=self.tasks_config["jd_analysis_task"],
            agent=self.jd_analyzer(),
        )

    @task
    def gap_analysis_task(self) -> Task:

        return Task(
            config=self.tasks_config["gap_analysis_task"],
            agent=self.gap_finder(),
            context=[self.resume_analysis_task(), self.jd_analysis_task()],
        )

    @task
    def skills_adivce_task(self) -> Task:

        return Task(
            config=self.tasks_config["skills_advice_task"],
            agent=self.skills_advisor(),
            context=[self.gap_analysis_task()],
        )

    @task
    def cover_letter_task(self) -> Task:

        return Task(
            config=self.tasks_config["cover_letter_task"],
            agent=self.cover_letter_writer(),
            context=[
                self.resume_analysis_task(),
                self.jd_analysis_task(),
                self.gap_analysis_task(),
            ],
        )

    @crew
    def crew(self) -> Crew:

        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )


def build_and_run_crew(resume_text: str, job_description: str) -> dict:

    print("\nStep 1/5: Embedding resume into RAG pipeline...")
    collection = embedder.embed_resume(resume_text)

    resume_context = retriever.retrieve_full_context(collection)
    print(f"\nStep 2/5: Connecting to LLM ({ACTIVE_MODEL})...")

    llm = _make_llm()
    print("Connected to LLM")

    print("\n👥 Step 3/5: Building CrewAI agents...")

    job_crew = JobCrew(llm=llm)
    print(
        "Agents:  Resume Analyst · JD Analyzer · Gap Finder · Skills Advisor · Cover Letter Writer"
    )
    print(
        "Tasks:   resume_analysis → jd_analysis → gap_analysis → skills_advice → cover_letter"
    )

    print("\n Step 4/5: Creating tasks with context chain...")

    result = job_crew.crew().kickoff(
        inputs={
            "resume_context": resume_context,
            "job_description": job_description,
        }
    )

    print("\n Step 5/5: Running the crew (this takes 1-3 minutes)...")

    tasks = job_crew.crew().tasks

    def _raw(t):
        return t.output.raw if t.output else ""

    outputs = {
        "resume_analysis": _raw(tasks[0]),
        "jd_analysis": _raw(tasks[1]),
        "gap_analysis": _raw(tasks[2]),
        "skills_plan": _raw(tasks[3]),
        "cover_letter": _raw(tasks[4]),
        "full_result": str(result),
    }

    outputs["report_path"] = _save_report(outputs)
    return outputs
